
CREATE USER DEVELOPERS IDENTIFIED BY RMLIT2024DEV
GRANT CREATE SESSION TO DEVELOPERS;
GRANT CONNECT TO DEVELOPERS;
GRANT ALL PRIVILEGES TO DEVELOPERS;
CONN DEVELOPERS/RMLIT2024DEV@ORCL


CREATE USER JOY IDENTIFIED BY RMLIT2024JOY;
GRANT CREATE SESSION TO JOY;
GRANT CONNECT TO JOY;
GRANT ALL PRIVILEGES TO JOY;

CREATE USER COUPON_SERVICE IDENTIFIED BY RMLIT2024CUP;
GRANT CREATE SESSION TO COUPON_SERVICE;
GRANT CONNECT TO COUPON_SERVICE;
GRANT ALL PRIVILEGES TO COUPON_SERVICE;

CREATE USER SYS IDENTIFIED BY orcle;
GRANT CREATE SESSION TO SYS;
GRANT CONNECT TO SYS;
GRANT ALL PRIVILEGES TO SYS;

CREATE USER TA_TD IDENTIFIED BY RMLIT2025TA_TD;
GRANT CREATE SESSION TO TA_TD;
GRANT CONNECT TO TA_TD;
GRANT ALL PRIVILEGES TO TA_TD;


-- CREATE USER INSURANCE_SERVICE IDENTIFIED BY RMLIT2026INC;
-- GRANT CREATE SESSION TO INSURANCE_SERVICE;
-- GRANT CONNECT TO INSURANCE_SERVICE;
-- GRANT ALL PRIVILEGES TO INSURANCE_SERVICE;

CREATE USER INSURANCE_SERVICE IDENTIFIED BY "RMLIT2026INC"
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users;

GRANT CREATE SESSION TO INSURANCE_SERVICE;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO INSURANCE_SERVICE;
