
CREATE USER DEVELOPERS IDENTIFIED BY RMLIT2024DEV
GRANT CREATE SESSION TO DEVELOPERS;
GRANT CONNECT TO DEVELOPERS;
GRANT ALL PRIVILEGES TO DEVELOPERS;
CONN DEVELOPERS/RMLIT2024DEV@ORCL


CREATE USER JOY IDENTIFIED BY RMLIT2024JOY;
GRANT CREATE SESSION TO JOY;
GRANT CONNECT TO JOY;
GRANT ALL PRIVILEGES TO JOY;