SELECT  
    U.EMP_NAME,
    u.RML_ID,
    u.R_CONCERN,
    u.MOBILE_NO,
    u.MAIL,
    CASE 
        WHEN p.EMP_ID IS NULL THEN 'NOT_CREATE_PMS'
        WHEN p.SELF_SUBMITTED_STATUS = 1 THEN 'SUBMITED_PMS'
        ELSE 'NOT_SUBMITED'
    END AS PMS_SUBMIT_STATUS
FROM 
    RML_HR_APPS_USER u
LEFT JOIN 
    HR_PMS_EMP p
ON 
    u.RML_ID = p.EMP_ID
ORDER BY  u.RML_ID;