SELECT  
    U.EMP_NAME,
    u.RML_ID,
    u.R_CONCERN,
    u.MOBILE_NO,
    u.MAIL,
    CASE 
        WHEN p.EMP_ID IS NULL THEN 'NOT_CREATE_PMS'
        WHEN p.SELF_SUBMITTED_STATUS = 1 THEN 'SUBMITED_PMS'
        ELSE 'NOT_SUBMITED'
    END AS PMS_SUBMIT_STATUS
FROM 
    RML_HR_APPS_USER u
LEFT JOIN 
    HR_PMS_EMP p
ON 
    u.RML_ID = p.EMP_ID
    WHERE u.IS_ACTIVE = 1
ORDER BY  u.RML_ID
GROUP BY R_CONCERN;



///SUMMARY REPORT

SELECT 
    'PMS Created, But Not Submitted' AS STATUS,
    COUNT(CASE WHEN u.R_CONCERN = 'RML' THEN u.RML_ID END) AS RML,
    COUNT(CASE WHEN u.R_CONCERN = 'RMWL' THEN u.RML_ID END) AS RMWL,
    COUNT(CASE WHEN u.R_CONCERN = 'RCL' THEN u.RML_ID END) AS RCL,
    COUNT(CASE WHEN u.R_CONCERN = 'RCVL' THEN u.RML_ID END) AS RCVL,
    COUNT(CASE WHEN u.R_CONCERN = 'RREL' THEN u.RML_ID END) AS RREL,
    COUNT(CASE WHEN u.R_CONCERN = 'BdR' THEN u.RML_ID END) AS BdR,
    COUNT(CASE WHEN u.R_CONCERN = 'SASH' THEN u.RML_ID END) AS SASH,
    COUNT(CASE WHEN u.R_CONCERN = 'RIL' THEN u.RML_ID END) AS RIL
FROM RML_HR_APPS_USER u
LEFT JOIN HR_PMS_EMP p ON u.RML_ID = p.EMP_ID
WHERE u.IS_ACTIVE = 1
AND p.EMP_ID IS NOT NULL
AND (p.SELF_SUBMITTED_STATUS = 0 OR p.SELF_SUBMITTED_STATUS IS NULL)

UNION ALL

SELECT 
    'PMS Submitted' AS STATUS,
    COUNT(CASE WHEN u.R_CONCERN = 'RML' THEN u.RML_ID END) AS RML,
    COUNT(CASE WHEN u.R_CONCERN = 'RMWL' THEN u.RML_ID END) AS RMWL,
    COUNT(CASE WHEN u.R_CONCERN = 'RCL' THEN u.RML_ID END) AS RCL,
    COUNT(CASE WHEN u.R_CONCERN = 'RCVL' THEN u.RML_ID END) AS RCVL,
    COUNT(CASE WHEN u.R_CONCERN = 'RREL' THEN u.RML_ID END) AS RREL,
    COUNT(CASE WHEN u.R_CONCERN = 'BdR' THEN u.RML_ID END) AS BdR,
    COUNT(CASE WHEN u.R_CONCERN = 'SASH' THEN u.RML_ID END) AS SASH,
    COUNT(CASE WHEN u.R_CONCERN = 'RIL' THEN u.RML_ID END) AS RIL
FROM RML_HR_APPS_USER u
LEFT JOIN HR_PMS_EMP p ON u.RML_ID = p.EMP_ID
WHERE u.IS_ACTIVE = 1
AND p.EMP_ID IS NOT NULL
AND p.SELF_SUBMITTED_STATUS = 1

UNION ALL

SELECT 
    'PMS Not Yet Created' AS STATUS,
    COUNT(CASE WHEN u.R_CONCERN = 'RML' THEN u.RML_ID END) AS RML,
    COUNT(CASE WHEN u.R_CONCERN = 'RMWL' THEN u.RML_ID END) AS RMWL,
    COUNT(CASE WHEN u.R_CONCERN = 'RCL' THEN u.RML_ID END) AS RCL,
    COUNT(CASE WHEN u.R_CONCERN = 'RCVL' THEN u.RML_ID END) AS RCVL,
    COUNT(CASE WHEN u.R_CONCERN = 'RREL' THEN u.RML_ID END) AS RREL,
    COUNT(CASE WHEN u.R_CONCERN = 'BdR' THEN u.RML_ID END) AS BdR,
    COUNT(CASE WHEN u.R_CONCERN = 'SASH' THEN u.RML_ID END) AS SASH,
    COUNT(CASE WHEN u.R_CONCERN = 'RIL' THEN u.RML_ID END) AS RIL
FROM RML_HR_APPS_USER u
LEFT JOIN HR_PMS_EMP p ON u.RML_ID = p.EMP_ID
WHERE u.IS_ACTIVE = 1
AND p.EMP_ID IS NULL

UNION ALL

SELECT 
    'Grand Total' AS STATUS,
    COUNT(CASE WHEN u.R_CONCERN = 'RML' THEN u.RML_ID END) AS RML,
    COUNT(CASE WHEN u.R_CONCERN = 'RMWL' THEN u.RML_ID END) AS RMWL,
    COUNT(CASE WHEN u.R_CONCERN = 'RCL' THEN u.RML_ID END) AS RCL,
    COUNT(CASE WHEN u.R_CONCERN = 'RCVL' THEN u.RML_ID END) AS RCVL,
    COUNT(CASE WHEN u.R_CONCERN = 'RREL' THEN u.RML_ID END) AS RREL,
    COUNT(CASE WHEN u.R_CONCERN = 'BdR' THEN u.RML_ID END) AS BdR,
    COUNT(CASE WHEN u.R_CONCERN = 'SASH' THEN u.RML_ID END) AS SASH,
    COUNT(CASE WHEN u.R_CONCERN = 'RIL' THEN u.RML_ID END) AS RIL
FROM RML_HR_APPS_USER u
WHERE u.IS_ACTIVE = 1;



RMWL
RCVL
RREL
RCL
RML
BdR
SASH
RIL